name: Release

env:
  IMAGE_NAME: activemq-artemis-broker

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      trigger_children:
        description: 'Trigger children'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: >
          sudo apt-get install gcc libkrb5-dev pass &&
          sudo pip install docker docker-squash cekit odcs[client]

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create release tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git fetch --tags
          HEAD_COMMIT="$(git rev-parse HEAD)"
          RELEASE_TAG="v$(grep -Po -m 1 '(?<=^version: ")[^"]+' image.yaml)"
          RELEASE_TAG_COMMIT="$(git rev-list -n 1 ${RELEASE_TAG} || true)"
          if [ "$RELEASE_TAG_COMMIT" != "$HEAD_COMMIT" ]; then
            git config user.name 'artemiscloud-bot'
            git config user.email 'bot@artemiscloud.io'
            git tag -a ${RELEASE_TAG} -m ${RELEASE_TAG} --force
            git push origin $RELEASE_TAG --force
          fi

      - name: Build the image
        run: "cekit --verbose build docker --tag $IMAGE_NAME:latest"

      - name: Push the image
        run: >
          RELEASE_TAG="$(git describe --exact-match --tags)" && IMAGE_TAG=${RELEASE_TAG#v} &&
          docker login --username=${{ secrets.QUAY_USERNAME }} --password=${{ secrets.QUAY_PASSWORD }} quay.io &&
          docker tag $IMAGE_NAME:latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:$IMAGE_TAG &&
          docker push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:$IMAGE_TAG &&
          docker tag $IMAGE_NAME:latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:latest &&
          docker push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:latest

      - name: Trigger children
        if: ${{ inputs.trigger_children }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'activemq-artemis-broker-kubernetes-image',
              workflow_id: 'update.yml',
              ref: 'main',
              inputs: {
                version: '*.*.+',
                update_version: 'true',
                base_image: 'latest',
                update_base_image: 'true',
                trigger_release: 'all'
              }
            });
